

[goldberg]
gh_user = "Detanup01"
gh_repo = "gbe_fork"
version = "release-2025_11_27"

[aoe2]
gh_companion_user = "luskaner"
gh_companion_repo = "ageLANServerLauncherCompanion"
gh_launcher_user = "luskaner"
gh_launcher_repo = "ageLANServer"
launcher_version = "v1.14"
